# Usamos una imagen oficial y ligera de Python
FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /apps

# ¡Adiós apt-get! Pasamos directo a instalar Python

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .