# Generated by Django 5.2 on 2025-11-17 15:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email address"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined"),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID único del usuario en Telegram",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True,
                        help_text="Username de Telegram (sin @)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Si el usuario quiere recibir notificaciones del bot",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("name", models.CharField(help_text="Nombre de la categoría", max_length=100)),
                (
                    "keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de palabras clave para auto-categorización (ej: ['uber', 'taxi'])",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, help_text="Si es una categoría global disponible para todos"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="#6B7280",
                        help_text="Color en formato HEX para UI (ej: #FF5733)",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario dueño de la categoría. NULL = categoría global",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "db_table": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeletedObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("object_id", models.PositiveIntegerField(help_text="ID del objeto original")),
                (
                    "object_data",
                    models.JSONField(help_text="Snapshot completo del objeto al momento de eliminarlo"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(auto_now_add=True, help_text="Cuándo se eliminó el objeto"),
                ),
                (
                    "reason",
                    models.CharField(blank=True, help_text="Razón de eliminación (opcional)", max_length=255),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Tipo de objeto eliminado (Expense, Category, etc.)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        help_text="Usuario que eliminó el objeto",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Objeto Eliminado",
                "verbose_name_plural": "Objetos Eliminados",
                "db_table": "deleted_objects",
                "ordering": ["-deleted_at"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto del gasto (debe ser mayor a 0)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Descripción del gasto (máx 500 caracteres)", max_length=500),
                ),
                (
                    "date",
                    models.DateTimeField(help_text="Fecha y hora del gasto (no puede ser futura)"),
                ),
                (
                    "raw_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Mensaje original enviado por el usuario (para auditoría)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Categoría del gasto (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="core.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario que registró el gasto",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto",
                "verbose_name_plural": "Gastos",
                "db_table": "expenses",
                "ordering": ["-date"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["telegram_id"], name="idx_telegram_id"),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("name", "user"),
                name="unique_category_per_user",
            ),
        ),
        migrations.AddIndex(
            model_name="deletedobject",
            index=models.Index(fields=["content_type", "object_id"], name="idx_content_object"),
        ),
        migrations.AddIndex(
            model_name="deletedobject",
            index=models.Index(fields=["deleted_at"], name="idx_deleted_at"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["user", "-date"], name="idx_user_date"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["user", "category"], name="idx_user_category"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["-date"], name="idx_date_desc"),
        ),
    ]
