# Generated by Django 5.2 on 2025-11-24 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorySuggestionFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "was_accepted",
                    models.BooleanField(help_text="Si el usuario aceptó la sugerencia"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expense",
                    models.ForeignKey(
                        help_text="Expense para el cual se hizo la sugerencia",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_feedbacks",
                        to="core.expense",
                    ),
                ),
                (
                    "final_category",
                    models.ForeignKey(
                        help_text="Categoría final elegida por el usuario",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestions_accepted",
                        to="core.category",
                    ),
                ),
                (
                    "suggested_category",
                    models.ForeignKey(
                        help_text="Categoría que sugirió el sistema",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestions_made",
                        to="core.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback de Sugerencia",
                "verbose_name_plural": "Feedbacks de Sugerencias",
                "db_table": "category_suggestion_feedbacks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["suggested_category", "was_accepted"],
                        name="idx_suggestion_accepted",
                    ),
                    models.Index(fields=["expense", "created_at"], name="idx_expense_feedback"),
                ],
            },
        ),
    ]
