# Generated by Django 5.2 on 2026-03-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_categorysuggestionfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pendiente"), ("confirmed", "Confirmado")],
                db_index=True,
                default="confirmed",
                help_text="Estado del gasto. 'pending'=esperando confirmacion de categoria",
                max_length=20,
            ),
        ),
    ]
