# Generated by Django 5.2 on 2026-07-26 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_add_status_to_expense"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("whatsapp", "WhatsApp")],
                        db_index=True,
                        help_text="Canal de mensajería",
                        max_length=32,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="ID nativo del usuario en el canal (from.id en Telegram, wa_id en WhatsApp)",
                        max_length=64,
                    ),
                ),
                (
                    "external_username",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Username en el canal, si el canal lo provee",
                        max_length=255,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre visible reportado por el canal",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario dueño de esta identidad",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Identidad de canal",
                "verbose_name_plural": "Identidades de canal",
                "db_table": "channel_identities",
                "indexes": [models.Index(fields=["user", "channel"], name="idx_user_channel")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("channel", "external_id"), name="unique_identity_per_channel"
                    )
                ],
            },
        ),
    ]
